### ISSUE TITLE
_links

### ISSUE THREAD

**Issue by NriotHrreion** [NriotHrreion/nin.red-comments#3]

**Comment by NriotHrreion** [comment]
欢迎交换友链！提交友链前请先将我的链接放到你的网站中~

**Comment by Chengzi600** [comment]
已加~
```yml
- url: "https://blog.zhaozilin.cn",
  avatar: "https://thirdqq.qlogo.cn/g?b=sdk&nk=2752718571&s=640",
  name: "橙の小站",
  blog: "橙の小站",
  desc: "靠自己，实际一些！",
  email: 2752718571@qq.com
  color: "#ffbf00ff"
```
